/**
 * Guild Content Matrix
 *
 * Maps every site pair to a contextually relevant blog post angle.
 * Each guild site writes about every other guild site, framed through
 * its own niche. 10 sites × 9 others = 90 content pieces.
 *
 * Used to generate content briefs and track publishing status.
 */

export interface ContentPiece {
  /** The site publishing the post */
  publisher: string;
  /** The guild site being written about */
  subject: string;
  /** Working title */
  title: string;
  /** The angle connecting publisher's niche to subject's niche */
  angle: string;
  /** Target keywords */
  keywords: string[];
  /** Suggested word count */
  wordCount: number;
  /** Status */
  status: "planned" | "drafted" | "published";
}

export const CONTENT_MATRIX: ContentPiece[] = [
  // ───────────────────────────────────────────────
  // JAPANESE JESUS publishes about...
  // ───────────────────────────────────────────────
  {
    publisher: "japanesejesus.com",
    subject: "wildmeatjapan.com",
    title: "What the Hunters of Aomori Know About the Jesus Trail",
    angle: "The matagi hunting tradition in Aomori overlaps with the geography of the Christ legend. Gibier culture and pilgrim culture share the same mountains.",
    keywords: ["aomori hunting", "matagi tradition", "jesus trail japan", "shingo village wildlife"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "japanesejesus.com",
    subject: "musicinjapan.com",
    title: "Sacred Sound: The Music That Follows Japan's Hidden Pilgrimages",
    angle: "Underground music and hidden legends share DNA — both exist outside the mainstream, both reward those who seek. Connects pilgrimage culture to the ethos of Japan's underground music scene.",
    keywords: ["japan pilgrimage music", "underground culture japan", "sacred sound japan"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "japanesejesus.com",
    subject: "japancraftbeer.com",
    title: "The Breweries Along the Shingo Pilgrimage Route",
    angle: "Mapping craft breweries in Aomori and Tohoku along the route a pilgrim might take to reach the Tomb of Christ. Beer as fuel for modern pilgrimage.",
    keywords: ["aomori craft beer", "tohoku brewery", "shingo village travel", "pilgrimage beer"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "japanesejesus.com",
    subject: "mkultraman.com",
    title: "How Japanese Jesus Was Built: ARG Design as Brand Strategy",
    angle: "Behind-the-scenes look at the digital strategy and ARG mechanics behind the site. Credits MKULTRAMAN as the consultancy that architected the experience.",
    keywords: ["ARG design", "alternate reality game strategy", "brand storytelling japan"],
    wordCount: 1800,
    status: "planned",
  },
  {
    publisher: "japanesejesus.com",
    subject: "akiyaz.io",
    title: "The Empty Houses on the Road to Christ's Tomb",
    angle: "Shingo and surrounding villages are full of akiya. The legend draws visitors, but the depopulation is real. Connects pilgrimage tourism to rural revitalization.",
    keywords: ["shingo village akiya", "aomori abandoned houses", "rural japan tourism", "depopulation japan"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "japanesejesus.com",
    subject: "kaalamusic.com",
    title: "From Tokyo Basements to Aomori Mountains: Underground Culture Has No Map",
    angle: "Kaala documented Tokyo's underground for 15 years. Japanese Jesus documents a buried legend. Both are acts of preservation against forgetting.",
    keywords: ["tokyo underground culture", "kaala music", "japan hidden culture", "cultural preservation"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "japanesejesus.com",
    subject: "heatherdobbin.com",
    title: "The Psychology of Pilgrimage: Why People Walk Toward Impossible Stories",
    angle: "Executive coach perspective on what drives people to seek meaning in improbable places. The psychology of belief, surrender, and transformation.",
    keywords: ["pilgrimage psychology", "why people believe", "transformative travel japan", "meaning seeking"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "japanesejesus.com",
    subject: "thedelphinetwork.com",
    title: "The Foreign Executives Who've Visited Christ's Tomb",
    angle: "Profiles of international business leaders in Japan who've made the trip to Shingo. What draws high-performing professionals to legendary sites.",
    keywords: ["shingo village visitors", "japan expat travel", "executive travel japan"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "japanesejesus.com",
    subject: "thomsmithart.com",
    title: "Drawing the Unseen: An Artist's Interpretation of the Jesus Legend",
    angle: "Commission or feature Thom Smith's visual interpretation of key moments from the legend. Art as a way to process myth.",
    keywords: ["japan legend art", "shingo illustration", "myth illustration", "thom smith art"],
    wordCount: 1200,
    status: "planned",
  },

  // ───────────────────────────────────────────────
  // WILD MEAT JAPAN publishes about...
  // ───────────────────────────────────────────────
  {
    publisher: "wildmeatjapan.com",
    subject: "japanesejesus.com",
    title: "Hunting in the Shadow of Christ's Tomb: Gibier in Aomori",
    angle: "Aomori's deer and boar populations are managed by the same rural communities that maintain the Shingo legend. The overlap of hunting grounds and sacred ground.",
    keywords: ["aomori gibier", "hunting aomori japan", "shingo village hunting", "wild game tohoku"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "wildmeatjapan.com",
    subject: "musicinjapan.com",
    title: "After the Hunt: Where Wild Game Meets Tokyo Nightlife",
    angle: "Tokyo izakayas and restaurants near live music venues that serve gibier. The overlap of underground culture and adventurous eating.",
    keywords: ["gibier tokyo restaurants", "wild game izakaya", "tokyo nightlife food", "adventurous eating tokyo"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "wildmeatjapan.com",
    subject: "japancraftbeer.com",
    title: "Pairing Wild Game with Japanese Craft Beer: A Regional Guide",
    angle: "Region-by-region pairing guide — Hokkaido venison with Hokkaido pilsners, Kyushu boar with local stouts. Two niche Japanese food cultures that complement each other.",
    keywords: ["gibier beer pairing", "japanese craft beer food", "wild game pairing", "venison craft beer"],
    wordCount: 2000,
    status: "planned",
  },
  {
    publisher: "wildmeatjapan.com",
    subject: "mkultraman.com",
    title: "Building Japan's First Wild Game Directory: A Digital Strategy Story",
    angle: "How the Wild Meat Japan directory was designed and built. The strategy behind making an invisible industry findable online.",
    keywords: ["food directory japan", "niche market strategy", "digital strategy japan food"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "wildmeatjapan.com",
    subject: "akiyaz.io",
    title: "Why Gibier Is the Economic Engine of Japan's Emptiest Villages",
    angle: "Rural depopulation creates a wildlife management crisis — and an opportunity. How the gibier industry and akiya revitalization share the same zip codes.",
    keywords: ["rural japan economy", "gibier industry japan", "akiya revitalization", "depopulation wildlife"],
    wordCount: 1800,
    status: "planned",
  },
  {
    publisher: "wildmeatjapan.com",
    subject: "kaalamusic.com",
    title: "Blood and Bass: When Tokyo's Underground Scene Eats Wild",
    angle: "Feature on punk/metal musicians who hunt, or venues that serve gibier. The gritty overlap of underground music culture and wild food.",
    keywords: ["tokyo punk culture food", "underground japan lifestyle", "musicians who hunt"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "wildmeatjapan.com",
    subject: "heatherdobbin.com",
    title: "The Mindful Hunter: What Gibier Teaches About Presence",
    angle: "Hunting requires deep presence and patience — qualities at the core of executive coaching. The parallels between tracking game and tracking personal growth.",
    keywords: ["mindful hunting", "presence in nature japan", "hunting meditation", "nature leadership"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "wildmeatjapan.com",
    subject: "thedelphinetwork.com",
    title: "Japan's Wild Game Industry: A Briefing for Foreign Investors",
    angle: "Market overview of Japan's gibier industry for the executive/investor audience. Regulations, market size, opportunity areas.",
    keywords: ["japan gibier market", "wild game business japan", "japan food industry investment"],
    wordCount: 1800,
    status: "planned",
  },
  {
    publisher: "wildmeatjapan.com",
    subject: "thomsmithart.com",
    title: "The Art of the Hunt: Gibier Illustration and Design in Japan",
    angle: "Visual culture around hunting in Japan — from traditional prints to modern gibier branding. Feature on Thom Smith's illustration work in the context of food packaging and identity.",
    keywords: ["gibier branding japan", "food illustration japan", "hunting art japan"],
    wordCount: 1200,
    status: "planned",
  },

  // ───────────────────────────────────────────────
  // MUSIC IN JAPAN publishes about...
  // ───────────────────────────────────────────────
  {
    publisher: "musicinjapan.com",
    subject: "japanesejesus.com",
    title: "The Bands Playing the Legend: Music Inspired by Japan's Christ Myth",
    angle: "Japanese metal, doom, and noise bands that draw on religious and occult themes. The Shingo legend as inspiration for underground art.",
    keywords: ["japanese metal religious themes", "occult japan music", "doom metal japan"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "musicinjapan.com",
    subject: "wildmeatjapan.com",
    title: "Festival Food Gone Wild: Gibier at Japan's Outdoor Music Events",
    angle: "Regional music festivals increasingly feature local gibier vendors. Mapping the intersection of live music and wild food at outdoor events.",
    keywords: ["japan music festival food", "outdoor festival gibier", "fuji rock food", "festival food japan"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "musicinjapan.com",
    subject: "japancraftbeer.com",
    title: "The Tap List at Tokyo's Best Live Houses",
    angle: "Venue-by-venue guide to what craft beer you can actually drink at Tokyo's underground venues. Where music and brewing culture overlap.",
    keywords: ["tokyo live house beer", "craft beer music venue tokyo", "live music drinks japan"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "musicinjapan.com",
    subject: "mkultraman.com",
    title: "How Music In Japan Was Built: From Scene Knowledge to Platform",
    angle: "The digital strategy behind turning 15 years of scene experience into a searchable platform. Credits MKULTRAMAN's approach to niche media.",
    keywords: ["music platform design", "niche media strategy", "underground music platform"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "musicinjapan.com",
    subject: "akiyaz.io",
    title: "Sound in Empty Spaces: Musicians Moving to Rural Japan",
    angle: "Musicians buying cheap akiya to build rehearsal spaces and recording studios in depopulated areas. The quiet revolution of rural creative migration.",
    keywords: ["rural japan music", "akiya recording studio", "musicians rural japan", "creative migration japan"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "musicinjapan.com",
    subject: "kaalamusic.com",
    title: "Kaala to Music In Japan: 15 Years of Documenting the Underground",
    angle: "The origin story — how Kaala Music's decade of documentation laid the foundation for Music In Japan. An archive of the evolution.",
    keywords: ["kaala music history", "tokyo underground history", "japan punk history", "music in japan origin"],
    wordCount: 2000,
    status: "planned",
  },
  {
    publisher: "musicinjapan.com",
    subject: "heatherdobbin.com",
    title: "Burnout in the Scene: What Musicians Can Learn from Executive Coaching",
    angle: "Underground musicians face burnout, identity crisis, and unsustainable lifestyles. Executive coaching principles applied to creative careers.",
    keywords: ["musician burnout japan", "creative burnout", "coaching for musicians", "artist mental health"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "musicinjapan.com",
    subject: "thedelphinetwork.com",
    title: "When Executives Mosh: Japan's Business Leaders with Underground Taste",
    angle: "Profiles of Delphi Network-type professionals who are secret fans of the underground scene. The hidden overlap of boardrooms and basements.",
    keywords: ["japan executive culture", "underground music fans japan", "business leaders music"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "musicinjapan.com",
    subject: "thomsmithart.com",
    title: "The Artists Behind Tokyo's Best Gig Posters",
    angle: "Feature on Thom Smith and the broader gig poster scene. How visual art defines the identity of Tokyo's underground music community.",
    keywords: ["tokyo gig poster", "concert poster art japan", "thom smith art", "underground poster design"],
    wordCount: 1500,
    status: "planned",
  },

  // ───────────────────────────────────────────────
  // JAPAN CRAFT BEER publishes about...
  // ───────────────────────────────────────────────
  {
    publisher: "japancraftbeer.com",
    subject: "japanesejesus.com",
    title: "Holy Water: Craft Breweries in Aomori and the Tohoku Pilgrimage Belt",
    angle: "Aomori and Tohoku have a growing craft beer scene. Frame it through the lens of the pilgrimage route to Shingo.",
    keywords: ["aomori craft beer", "tohoku brewery guide", "craft beer pilgrimage japan"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "japancraftbeer.com",
    subject: "wildmeatjapan.com",
    title: "Wild Pairings: A Brewer's Guide to Japanese Game Meat",
    angle: "Collaboration between brewers and gibier processors. Styles that pair with venison, boar, and bear. Tasting notes and regional combinations.",
    keywords: ["craft beer food pairing japan", "gibier beer pairing", "japanese game meat beer"],
    wordCount: 2000,
    status: "planned",
  },
  {
    publisher: "japancraftbeer.com",
    subject: "musicinjapan.com",
    title: "Best Craft Beer Near Tokyo's Live Music Venues",
    angle: "Venue-adjacent taproom guide. Where to drink before and after shows at Shelter, Earthdom, Antiknock, etc.",
    keywords: ["craft beer shibuya", "shimokitazawa taproom", "tokyo live music beer", "koenji craft beer"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "japancraftbeer.com",
    subject: "mkultraman.com",
    title: "How We Mapped 800+ Breweries: Building a Craft Beer Intelligence Platform",
    angle: "The data architecture and scraping strategy behind the platform. Credits MKULTRAMAN's approach to niche business intelligence.",
    keywords: ["brewery data japan", "craft beer analytics", "business intelligence platform", "brewery directory"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "japancraftbeer.com",
    subject: "akiyaz.io",
    title: "Brewing in the Countryside: Craft Beer and Rural Revitalization",
    angle: "Microbreweries opening in depopulated areas — akiya converted to brewpubs, farmhouse ales from abandoned rice paddies. Craft beer as a rural revival tool.",
    keywords: ["rural brewery japan", "countryside craft beer", "akiya brewery", "rural revitalization beer"],
    wordCount: 1800,
    status: "planned",
  },
  {
    publisher: "japancraftbeer.com",
    subject: "kaalamusic.com",
    title: "Brewery Taprooms That Double as Live Venues",
    angle: "The overlap of craft beer culture and live music — breweries that host shows, and the Kaala-documented venues that pour good beer.",
    keywords: ["brewery live music japan", "taproom concerts tokyo", "beer and music japan"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "japancraftbeer.com",
    subject: "heatherdobbin.com",
    title: "Leadership Lessons from Japan's Craft Brewery Founders",
    angle: "Profiles of brewery founders through a leadership lens. What executive coaching principles show up in successful brewery leadership.",
    keywords: ["brewery founder japan", "craft beer leadership", "japan entrepreneur leadership"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "japancraftbeer.com",
    subject: "thedelphinetwork.com",
    title: "Craft Beer as Corporate Diplomacy in Japan",
    angle: "How foreign executives use craft beer culture for networking and relationship-building in Japan's business landscape.",
    keywords: ["japan business culture beer", "corporate networking japan", "craft beer business japan"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "japancraftbeer.com",
    subject: "thomsmithart.com",
    title: "Label Art: The Visual Identity of Japanese Craft Beer",
    angle: "Feature on craft beer label design in Japan, with Thom Smith's illustration work as a case study. How visual identity drives brand in a crowded market.",
    keywords: ["craft beer label design", "japanese beer art", "brewery branding japan", "beer label illustration"],
    wordCount: 1500,
    status: "planned",
  },

  // ───────────────────────────────────────────────
  // MKULTRAMAN publishes about...
  // ───────────────────────────────────────────────
  {
    publisher: "mkultraman.com",
    subject: "japanesejesus.com",
    title: "Building an ARG That People Actually Play: The Japanese Jesus Case Study",
    angle: "Deep dive into the strategy, design, and execution of Japanese Jesus as an alternate reality game. What worked, what didn't, what's next.",
    keywords: ["ARG case study", "alternate reality game design", "interactive storytelling strategy"],
    wordCount: 2500,
    status: "planned",
  },
  {
    publisher: "mkultraman.com",
    subject: "wildmeatjapan.com",
    title: "Making an Invisible Industry Findable: The Wild Meat Japan SEO Strategy",
    angle: "How we built a directory for an industry that barely exists online. SEO, data architecture, and content strategy for a niche nobody's serving.",
    keywords: ["niche SEO strategy", "directory SEO", "japan food industry digital", "niche market strategy"],
    wordCount: 2000,
    status: "planned",
  },
  {
    publisher: "mkultraman.com",
    subject: "musicinjapan.com",
    title: "From Scene Cred to Platform: Turning 15 Years of Music Knowledge into a Product",
    angle: "How deep domain expertise becomes a scalable digital product. The Music In Japan platform as a case study in scene-to-product strategy.",
    keywords: ["niche platform strategy", "scene knowledge product", "music platform case study"],
    wordCount: 2000,
    status: "planned",
  },
  {
    publisher: "mkultraman.com",
    subject: "japancraftbeer.com",
    title: "Agent Swarms and Business Intelligence: How We Track 800+ Breweries",
    angle: "Technical deep dive into the automated data collection and analysis system. How AI agents power a niche intelligence platform.",
    keywords: ["AI agent swarm", "business intelligence platform", "automated data collection", "brewery analytics"],
    wordCount: 2000,
    status: "planned",
  },
  {
    publisher: "mkultraman.com",
    subject: "akiyaz.io",
    title: "Selling Empty Houses to the World: Digital Strategy for Rural Japan",
    angle: "How Akiyaz positions a uniquely Japanese problem for an international audience. SEO, content strategy, and brand design for the akiya market.",
    keywords: ["akiya marketing", "japan real estate digital strategy", "rural japan branding"],
    wordCount: 1800,
    status: "planned",
  },
  {
    publisher: "mkultraman.com",
    subject: "kaalamusic.com",
    title: "The 15-Year Platform: What Kaala Music Teaches About Longevity in Niche Media",
    angle: "Most niche media dies in 2 years. Kaala survived 15. What that teaches about sustainable brand building in small markets.",
    keywords: ["niche media longevity", "sustainable brand building", "independent media strategy"],
    wordCount: 1800,
    status: "planned",
  },
  {
    publisher: "mkultraman.com",
    subject: "heatherdobbin.com",
    title: "When Your Client Is a Coach: Designing a Brand for Executive Presence",
    angle: "Case study in building a personal brand for a high-trust profession. How design choices communicate competence, warmth, and authority.",
    keywords: ["personal brand strategy", "executive coaching brand", "trust-first design"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "mkultraman.com",
    subject: "thedelphinetwork.com",
    title: "Building an Exclusive Network in a Skeptical Market",
    angle: "The Delphi Network as a case study in premium positioning. How to build exclusivity without alienating the audience you need.",
    keywords: ["premium brand strategy", "exclusive network design", "japan business networking"],
    wordCount: 1800,
    status: "planned",
  },
  {
    publisher: "mkultraman.com",
    subject: "thomsmithart.com",
    title: "The Illustrator's Brand: How Visual Artists Should Think About Digital Presence",
    angle: "Most artists have terrible websites. Thom Smith's site as a case study in portfolio design, SEO for artists, and digital visibility.",
    keywords: ["artist portfolio strategy", "illustrator SEO", "creative portfolio design"],
    wordCount: 1500,
    status: "planned",
  },

  // ───────────────────────────────────────────────
  // AKIYAZ publishes about...
  // ───────────────────────────────────────────────
  {
    publisher: "akiyaz.io",
    subject: "japanesejesus.com",
    title: "Pilgrimage Tourism and Rural Revival: Can Legends Save Dying Villages?",
    angle: "Shingo's Christ legend draws visitors to one of Japan's most depopulated areas. Can pilgrimage tourism fund akiya restoration?",
    keywords: ["pilgrimage tourism japan", "rural tourism revival", "shingo village tourism", "akiya tourism"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "akiyaz.io",
    subject: "wildmeatjapan.com",
    title: "The Gibier Economy: How Wild Game Is Keeping Rural Japan Alive",
    angle: "Gibier processing creates jobs in exactly the places that akiya are most abundant. The economic connection between wildlife management and rural revival.",
    keywords: ["gibier rural economy", "wild game japan jobs", "rural japan economy", "hunting industry japan"],
    wordCount: 1800,
    status: "planned",
  },
  {
    publisher: "akiyaz.io",
    subject: "musicinjapan.com",
    title: "Sound in Empty Spaces: Why Musicians Are Buying Akiya",
    angle: "Cheap rural houses make perfect rehearsal spaces and home studios. Profiles of musicians who've bought akiya for creative purposes.",
    keywords: ["akiya music studio", "rural japan musicians", "cheap house japan music", "creative akiya use"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "akiyaz.io",
    subject: "japancraftbeer.com",
    title: "Akiya to Brewpub: Converting Abandoned Houses into Craft Breweries",
    angle: "Real examples and feasibility of turning akiya into microbreweries. Zoning, costs, and the growing trend of rural craft beer.",
    keywords: ["akiya brewery conversion", "rural brewpub japan", "abandoned house brewery", "craft beer rural japan"],
    wordCount: 2000,
    status: "planned",
  },
  {
    publisher: "akiyaz.io",
    subject: "mkultraman.com",
    title: "How Akiyaz Reaches International Buyers: Digital Strategy for a Japanese Niche",
    angle: "Behind the scenes of positioning akiya for foreign investors. The SEO and content strategy that makes a Japanese-only market accessible worldwide.",
    keywords: ["akiya digital strategy", "japan real estate marketing", "international buyer marketing"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "akiyaz.io",
    subject: "kaalamusic.com",
    title: "The DIY Spirit: What Akiya Renovators and Punk Bands Have in Common",
    angle: "Both communities build something from nothing with no budget. The parallel ethos of DIY renovation and DIY music culture.",
    keywords: ["DIY japan culture", "punk renovation", "akiya DIY", "maker culture japan"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "akiyaz.io",
    subject: "heatherdobbin.com",
    title: "Starting Over in the Countryside: The Emotional Journey of Akiya Buyers",
    angle: "Buying an abandoned house in rural Japan is a life reset. Executive coaching perspective on the psychology of radical change.",
    keywords: ["life change japan", "moving rural japan", "psychology of relocation", "starting over abroad"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "akiyaz.io",
    subject: "thedelphinetwork.com",
    title: "Rural Japan as a Strategic Investment: A Briefing for Foreign Executives",
    angle: "Akiya investment opportunity framed for the Delphi Network's executive audience. Market data, visa implications, ROI scenarios.",
    keywords: ["japan rural investment", "akiya investment guide", "foreign investment rural japan"],
    wordCount: 1800,
    status: "planned",
  },
  {
    publisher: "akiyaz.io",
    subject: "thomsmithart.com",
    title: "Artist Residencies in Abandoned Houses: The Akiya as Creative Studio",
    angle: "The concept of akiya as artist residency spaces. How visual artists like Thom Smith could use rural spaces for large-scale work.",
    keywords: ["artist residency japan", "akiya art studio", "rural japan art", "creative spaces japan"],
    wordCount: 1200,
    status: "planned",
  },

  // ───────────────────────────────────────────────
  // KAALA MUSIC publishes about...
  // ───────────────────────────────────────────────
  {
    publisher: "kaalamusic.com",
    subject: "japanesejesus.com",
    title: "The Occult Underground: Where Japan's Metal Scene Meets Its Myths",
    angle: "Japanese doom, black metal, and noise artists draw heavily on folk mythology and religious iconography. The Christ legend of Shingo fits right in.",
    keywords: ["japanese occult metal", "doom metal japan mythology", "underground music religion japan"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "kaalamusic.com",
    subject: "wildmeatjapan.com",
    title: "Eating Wild at the Show: Gibier and the Tokyo Underground Lifestyle",
    angle: "The underground scene's relationship with food culture — late-night gibier spots near venues, musicians who hunt.",
    keywords: ["tokyo underground food", "after show food tokyo", "gibier izakaya live music"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "kaalamusic.com",
    subject: "musicinjapan.com",
    title: "What Comes After Kaala: Music In Japan and the Next Chapter",
    angle: "The handoff from Kaala to Music In Japan — what changed, what expanded, and why the underground still needs documentation.",
    keywords: ["kaala music successor", "music in japan platform", "tokyo underground documentation"],
    wordCount: 1800,
    status: "planned",
  },
  {
    publisher: "kaalamusic.com",
    subject: "japancraftbeer.com",
    title: "The Venues With the Best Taps: Where Craft Beer and Live Music Overlap",
    angle: "Kaala's venue knowledge meets craft beer culture. A curated list of venues that take their beer list as seriously as their booking.",
    keywords: ["tokyo venue craft beer", "live house beer list", "best drinks music venue tokyo"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "kaalamusic.com",
    subject: "mkultraman.com",
    title: "How Kaala Stayed Alive for 15 Years: The Strategy Behind the Scene",
    angle: "Reflective piece on the digital strategy and brand decisions that kept Kaala running when most scene sites died. Credits MKULTRAMAN's role.",
    keywords: ["independent media survival", "scene website strategy", "niche media business model"],
    wordCount: 1800,
    status: "planned",
  },
  {
    publisher: "kaalamusic.com",
    subject: "akiyaz.io",
    title: "Escape the City: Musicians Building Lives in Rural Japan",
    angle: "Profiles of scene veterans who left Tokyo for the countryside. Akiya as escape hatch from the grind of city-based underground music.",
    keywords: ["musicians leaving tokyo", "rural japan music scene", "akiya musician"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "kaalamusic.com",
    subject: "heatherdobbin.com",
    title: "Scene Burnout Is Real: A Coaching Perspective on Underground Sustainability",
    angle: "Running shows, playing gigs, holding down a day job — the underground lifestyle is unsustainable by design. Executive coaching tools applied to creative sustainability.",
    keywords: ["scene burnout", "musician mental health japan", "creative sustainability coaching"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "kaalamusic.com",
    subject: "thedelphinetwork.com",
    title: "The Suits Who Mosh: Japan's Secret Underground Fans in Business",
    angle: "They wear suits by day and earplugs by night. Feature on professionals in the Delphi orbit who are secret supporters of the underground.",
    keywords: ["japan professionals underground music", "executive music fans", "tokyo secret scene"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "kaalamusic.com",
    subject: "thomsmithart.com",
    title: "Thom Smith: The Art That Defined a Scene",
    angle: "Career-spanning feature on Thom Smith's contributions to Tokyo's underground visual identity. Flyers, album covers, merch, and risograph prints.",
    keywords: ["thom smith tokyo art", "underground poster artist japan", "concert art tokyo", "risograph japan"],
    wordCount: 2000,
    status: "planned",
  },

  // ───────────────────────────────────────────────
  // HEATHER DOBBIN publishes about...
  // ───────────────────────────────────────────────
  {
    publisher: "heatherdobbin.com",
    subject: "japanesejesus.com",
    title: "Why Leaders Seek Impossible Stories: The Coaching Lesson in Pilgrimage",
    angle: "High-performing leaders often seek transformative experiences outside rational frameworks. The Shingo legend as a lens for discussing surrender, belief, and growth.",
    keywords: ["executive transformation", "leadership pilgrimage", "belief and leadership", "coaching insight"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "heatherdobbin.com",
    subject: "wildmeatjapan.com",
    title: "From Boardroom to Wilderness: What Hunting Teaches About Leadership",
    angle: "Nature immersion and hunting as executive development tools. Patience, presence, and decision-making under pressure.",
    keywords: ["nature leadership", "hunting leadership lessons", "executive wilderness", "presence coaching"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "heatherdobbin.com",
    subject: "musicinjapan.com",
    title: "What Underground Musicians Teach Us About Authentic Leadership",
    angle: "Underground artists lead without authority, build community without budget, and sustain purpose without external validation. Leadership lessons from the scene.",
    keywords: ["authentic leadership", "underground leadership lessons", "purpose driven leadership"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "heatherdobbin.com",
    subject: "japancraftbeer.com",
    title: "The Founder's Mindset: What Craft Brewery Leaders Get Right",
    angle: "Craft brewery founders often exhibit exceptional leadership qualities — risk tolerance, community building, long-term thinking. Coaching analysis of the founder archetype.",
    keywords: ["founder mindset", "brewery founder leadership", "entrepreneur coaching", "startup leadership"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "heatherdobbin.com",
    subject: "mkultraman.com",
    title: "Coaching the Strategist: Working with Creative Consultants",
    angle: "Creative consultants face unique leadership challenges — client management, scope creep, identity vs. output. Coaching perspective on the MKULTRAMAN archetype.",
    keywords: ["consultant coaching", "creative leadership", "strategist coaching", "consultant burnout"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "heatherdobbin.com",
    subject: "akiyaz.io",
    title: "The Courage to Start Over: Coaching Through Radical Life Changes",
    angle: "Buying an abandoned house abroad is a radical life decision. Coaching framework for navigating identity shifts, fear, and reinvention.",
    keywords: ["radical life change coaching", "reinvention coaching", "starting over abroad", "courage coaching"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "heatherdobbin.com",
    subject: "kaalamusic.com",
    title: "Sustaining Purpose Without Profit: Lessons from 15 Years of Kaala",
    angle: "Kaala ran for 15 years on passion, not profit. Coaching perspective on intrinsic motivation, purpose sustainability, and avoiding burnout in mission-driven work.",
    keywords: ["purpose driven work", "intrinsic motivation coaching", "sustainable passion", "burnout prevention"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "heatherdobbin.com",
    subject: "thedelphinetwork.com",
    title: "Networking Without Performing: How Authentic Connection Drives Business",
    angle: "Most executive networking feels performative. Coaching perspective on how vulnerability and authenticity — the Delphi Network's ethos — build stronger professional relationships.",
    keywords: ["authentic networking", "executive vulnerability", "professional relationship coaching"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "heatherdobbin.com",
    subject: "thomsmithart.com",
    title: "The Artist's Identity Crisis: Coaching Creative Professionals Through Transition",
    angle: "Visual artists face unique identity challenges — commercial vs. personal work, visibility vs. integrity. Coaching framework for creative professionals like Thom Smith.",
    keywords: ["artist identity coaching", "creative professional coaching", "artist transition", "creative identity"],
    wordCount: 1500,
    status: "planned",
  },

  // ───────────────────────────────────────────────
  // THE DELPHI NETWORK publishes about...
  // ───────────────────────────────────────────────
  {
    publisher: "thedelphinetwork.com",
    subject: "japanesejesus.com",
    title: "Off the Beaten Path: Executive Travel Destinations in Northern Japan",
    angle: "Shingo and the Christ Tomb as one of several unconventional executive retreat destinations in Tohoku and Hokkaido.",
    keywords: ["executive travel japan", "tohoku travel", "unconventional japan destinations", "business retreat japan"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "thedelphinetwork.com",
    subject: "wildmeatjapan.com",
    title: "Japan's Gibier Industry: Market Intelligence for Foreign Investors",
    angle: "Business briefing on Japan's wild game processing industry — market size, growth trajectory, regulatory landscape, and investment angles.",
    keywords: ["japan gibier investment", "wild game market japan", "japan food industry intelligence"],
    wordCount: 1800,
    status: "planned",
  },
  {
    publisher: "thedelphinetwork.com",
    subject: "musicinjapan.com",
    title: "Culture as Currency: Why Japan's Music Scene Matters for Business",
    angle: "Understanding Japan's underground culture signals deep market knowledge. How music scene literacy helps foreign executives build authentic Japanese relationships.",
    keywords: ["japan culture business", "cultural intelligence japan", "executive japan relationships"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "thedelphinetwork.com",
    subject: "japancraftbeer.com",
    title: "The Craft Beer Boom as a Market Indicator for Japan's Consumer Trends",
    angle: "Japan's craft beer growth reflects broader consumer shifts — premiumization, localism, experience over product. What executives should watch.",
    keywords: ["japan consumer trends", "craft beer market indicator", "japan premium market", "consumer insight japan"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "thedelphinetwork.com",
    subject: "mkultraman.com",
    title: "Finding the Right Digital Partner in Japan: What Executives Should Look For",
    angle: "Framework for evaluating digital agencies and consultancies in the Japan market. MKULTRAMAN as a case study in niche expertise.",
    keywords: ["digital agency japan", "japan consultancy selection", "digital partner japan"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "thedelphinetwork.com",
    subject: "akiyaz.io",
    title: "Rural Japan Real Estate: An Executive's Guide to Akiya Investment",
    angle: "Due diligence guide for the Delphi audience — legal framework, visa implications, ROI scenarios, and the macro trend of rural depopulation as opportunity.",
    keywords: ["akiya investment executive", "japan rural real estate guide", "japan property investment"],
    wordCount: 2000,
    status: "planned",
  },
  {
    publisher: "thedelphinetwork.com",
    subject: "kaalamusic.com",
    title: "Client Entertainment Beyond Karaoke: Japan's Underground Music Scene for Executives",
    angle: "Ditch the KTV box — take clients to a real show. Guide to navigating Japan's underground music scene as a networking tool.",
    keywords: ["japan client entertainment", "alternative networking japan", "underground music executive"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "thedelphinetwork.com",
    subject: "heatherdobbin.com",
    title: "Why Every Executive in Japan Needs a Coach",
    angle: "The unique pressures of leading in Japan — cultural isolation, decision fatigue, identity management. Why coaching is essential, not optional.",
    keywords: ["executive coaching japan", "japan leadership challenges", "expat executive support"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "thedelphinetwork.com",
    subject: "thomsmithart.com",
    title: "Commissioning Art for Your Japan Office: A Guide to Working with Local Artists",
    angle: "How to commission original artwork from Tokyo-based artists like Thom Smith. Budget, process, and why original art beats generic corporate decor.",
    keywords: ["commission art japan", "office art tokyo", "corporate art japan", "thom smith commission"],
    wordCount: 1200,
    status: "planned",
  },

  // ───────────────────────────────────────────────
  // THOM SMITH ART publishes about...
  // ───────────────────────────────────────────────
  {
    publisher: "thomsmithart.com",
    subject: "japanesejesus.com",
    title: "Illustrating the Impossible: Visual Interpretations of the Jesus Legend",
    angle: "An artist's visual exploration of the Shingo legend — key scenes, symbols, and the challenge of depicting a myth that lives between cultures.",
    keywords: ["myth illustration", "legend art", "japan jesus art", "cultural illustration"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "thomsmithart.com",
    subject: "wildmeatjapan.com",
    title: "Drawing the Kill: The Visual Language of Japan's Hunting Culture",
    angle: "From traditional ukiyo-e hunting scenes to modern gibier branding — the visual history and future of hunting imagery in Japan.",
    keywords: ["hunting art japan", "gibier illustration", "ukiyo-e hunting", "food illustration japan"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "thomsmithart.com",
    subject: "musicinjapan.com",
    title: "Designing for Sound: How I Make Art for Tokyo's Underground",
    angle: "Process piece on creating gig posters, album art, and merch for bands in the Music In Japan ecosystem. Visual identity as sonic identity.",
    keywords: ["gig poster process", "album art process", "music illustration", "band merch design"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "thomsmithart.com",
    subject: "japancraftbeer.com",
    title: "The Art of the Label: Designing for Japan's Craft Beer Market",
    angle: "Label design breakdown — what works on a Japanese beer shelf, printing constraints, and the creative brief process for breweries.",
    keywords: ["beer label design", "craft beer branding", "packaging illustration japan", "label art process"],
    wordCount: 1500,
    status: "planned",
  },
  {
    publisher: "thomsmithart.com",
    subject: "mkultraman.com",
    title: "Working with a Strategist: How MKULTRAMAN Changed How I Present My Art",
    angle: "An artist's experience working with a digital strategist — how thinking about brand, SEO, and positioning changed the way art gets seen.",
    keywords: ["artist brand strategy", "illustrator digital presence", "artist portfolio strategy"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "thomsmithart.com",
    subject: "akiyaz.io",
    title: "The Akiya Studio: Dreaming of a Rural Art Practice in Japan",
    angle: "The concept of converting an abandoned house into a dedicated art studio. Space, light, cost, and the appeal of working outside Tokyo.",
    keywords: ["rural art studio japan", "akiya art space", "artist studio japan", "creative countryside japan"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "thomsmithart.com",
    subject: "kaalamusic.com",
    title: "15 Years of Scene Art: My Work with Kaala Music",
    angle: "Retrospective on creating visual identity for Kaala and the bands in its orbit. The evolution of Tokyo underground aesthetics through one artist's lens.",
    keywords: ["tokyo underground art", "kaala visual identity", "scene art retrospective", "punk art japan"],
    wordCount: 2000,
    status: "planned",
  },
  {
    publisher: "thomsmithart.com",
    subject: "heatherdobbin.com",
    title: "The Art of Letting Go: What Coaching Taught Me About Creative Practice",
    angle: "Personal essay on working with a coach and how it changed creative output — perfectionism, fear of visibility, and finding sustainable practice.",
    keywords: ["creative coaching", "artist personal growth", "creative practice sustainability"],
    wordCount: 1200,
    status: "planned",
  },
  {
    publisher: "thomsmithart.com",
    subject: "thedelphinetwork.com",
    title: "Art for the Office: What Executives Should Know About Commissioning Illustration",
    angle: "Practical guide to commissioning custom art — pricing, timelines, usage rights, and why original illustration beats stock imagery for professional spaces.",
    keywords: ["commission illustration guide", "custom art business", "corporate illustration", "art commissioning"],
    wordCount: 1200,
    status: "planned",
  },
];
